import { AppHeader } from '@/components/AppHeader';
import { AppFooter } from '@/components/AppFooter';
import { createSupabaseAdmin } from '@/lib/auth/admin';
import { createProfile, updateProfile } from '@/lib/actions/profiles';
import { requireAdmin } from '@/lib/auth/profile';

function formatDate(value?: string | null) { if (!value) return '-'; return new Intl.DateTimeFormat('it-IT', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)); }

export default async function UsersPage() {
  const current = await requireAdmin();
  const supabase = createSupabaseAdmin();
  const { data: profiles, error } = await supabase.from('staff_access').select('id, full_name, email, role, is_active, created_at').order('created_at', { ascending: false });
  const { data: authUsers } = await supabase.auth.admin.listUsers();
  const authByEmail = new Map((authUsers?.users ?? []).map((user) => [user.email?.toLowerCase(), user]));

  return <><main><AppHeader /><div className="container page"><header className="page-header"><div><p className="eyebrow">Staff</p><h1 className="page-title">Utenti e autorizzazioni</h1><p className="muted">Autorizza admin e operatori prima del primo accesso. Lo stato mostra se l'utente ha già effettuato il login.</p></div></header><section className="card" style={{ marginBottom: 24 }}><div className="page-header" style={{ marginBottom: 18 }}><div><h2 style={{ margin: 0 }}>Aggiungi accesso staff</h2><p className="muted">Inserisci email e ruolo. L'utente potrà accedere solo se attivo.</p></div></div><form action={createProfile} className="form-grid"><label><span>Nome</span><input name="full_name" /></label><label><span>Email</span><input name="email" type="email" required /></label><label><span>Ruolo</span><select name="role"><option value="operator">Operatore</option><option value="admin">Admin</option></select></label><div style={{ display: 'flex', alignItems: 'end' }}><button className="btn btn-primary" type="submit">Autorizza</button></div></form></section>{error ? <div className="card" style={{ color: 'var(--wine)', marginBottom: 24 }}>Errore caricamento: {error.message}</div> : null}<section className="card table-wrap"><table className="table"><thead><tr><th>Nome</th><th>Email</th><th>Ruolo</th><th>Stato</th><th>Ultimo accesso</th><th>Attivo</th><th></th></tr></thead><tbody>{(profiles ?? []).map((item) => { const authUser = authByEmail.get(item.email.toLowerCase()); const isMe = item.email.toLowerCase() === current.email; const status = !item.is_active ? 'Disattivato' : authUser ? 'Accesso effettuato' : 'Pending'; return <tr key={item.id}><td><input form={`profile-${item.id}`} name="full_name" defaultValue={item.full_name ?? ''} />{isMe ? <span className="badge" style={{ marginTop: 8 }}>Sei tu</span> : null}</td><td>{item.email}<input form={`profile-${item.id}`} type="hidden" name="email" value={item.email} /></td><td><select form={`profile-${item.id}`} name="role" defaultValue={item.role}><option value="operator">Operatore</option><option value="admin">Admin</option></select></td><td><span className="badge">{status}</span></td><td>{formatDate(authUser?.last_sign_in_at)}</td><td><input form={`profile-${item.id}`} type="checkbox" name="is_active" defaultChecked={item.is_active} disabled={isMe} /></td><td><form id={`profile-${item.id}`} action={updateProfile}><input type="hidden" name="id" value={item.id} />{isMe ? <input type="hidden" name="is_active" value="on" /> : null}<button className="btn btn-secondary" type="submit">Salva</button></form></td></tr>; })}{(profiles ?? []).length === 0 ? <tr><td colSpan={7} className="muted">Nessun accesso staff configurato.</td></tr> : null}</tbody></table></section></div></main><AppFooter /></>;
}
